[project]
name = "ci-cd-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.127.1",
    "httpx>=0.28.1",
    "uvicorn>=0.40.0",
]
